require 'rubygems'
require 'sqlite3'

@db = SQLite3::Database.new( "development.sqlite3" )

hiragana = {
  'あ' => 'a',
  'い' => 'i'   ,
  'う' => 'u'   ,
  'え' => 'e'   ,
  'お' => 'o'   ,
  'か' => 'ka'  ,
  'き' => 'ki'  ,
  'く' => 'ku'  ,
  'け' => 'ke'  ,
  'こ' => 'ko'  ,
  'さ' =>'sa'   ,
  'す' =>'su'   ,
  'せ' =>'se'   ,
  'そ' =>'so'   ,
  'た' =>'ta'   ,
  'ち' =>'chi'  ,
  'つ' =>'tsu'  ,
  'て' =>'te'   ,
  'と' => 'to',
  'な' =>'na'   ,
  'に' =>'ni'   ,
  'ぬ' =>'nu'   ,
  'ね' =>'ne'   ,
  'の' =>'no'   ,
  'は' =>'ha'   ,
  'ひ' =>'hi'   ,
  'ふ' =>'fu'   ,
  'へ' =>'he'   ,
  'ほ' =>'ho'   ,
  'ま' =>'ma'   ,
  'み' =>'mi'   ,
  'む' =>'mu'   ,
  'め' =>'me'   ,
  'も' =>'mo'   ,
  'や' => 'ya'  ,
  'ゆ' => 'yu'  ,
  'よ' => 'yo'  ,
  'ら' => 'ra'  ,
  'り' => 'ri'  ,
  'る' => 'ru'  ,
  'れ' => 're'  ,
  'ろ' => 'ro'  ,
  'わ' => 'wa'  ,
  'ゐ' => 'wi'  ,
  'ゑ' => 'we'  ,
  'を' => 'wo'  ,
  'ん' => 'n '  ,
  'が' => 'ga'  ,
  'ぎ' => 'gi'  ,
  'ぐ' => 'gu'  ,
  'げ' => 'ge'  ,
  'ご' => 'go'  ,
  'ざ' => 'za'  ,
  'じ' => 'ji'  ,
  'ず' => 'zu'  ,
  'ぜ' => 'ze'  ,
  'ぞ' => 'zo'  ,
  'だ' => 'da'  ,
  'ぢ' => 'ji'  ,
  'づ' => 'zu'  ,
  'で' => 'de'  ,
  'ど' => 'do'  ,
  'ば' => 'ba'  ,
  'び' => 'bi'  ,
  'ぶ' => 'bu'  ,
  'べ' => 'be'  ,
  'ぼ' => 'bo'  ,
  'ぱ' => 'pa'  ,
  'ぴ' => 'pi'  ,
  'ぷ' => 'pu'  ,
  'ぺ' => 'pe'  ,
  'ぽ' => 'po'  ,
  'ゔ' => 'vu'
}
katakana = {
  'ア' => 'a'  ,
  'イ' => 'i'  ,
  'ウ' => 'u'  ,
  'エ' => 'e'  ,
  'オ' => 'o'  ,
  'カ' => 'ka' ,
  'キ' => 'ki' ,
  'ク' => 'ku' ,
  'ケ' => 'ke' ,
  'コ' => 'ko' ,
  'サ' => 'sa' ,
  'シ' => 'shi',
  'ス' => 'su' ,
  'セ' => 'se' ,
  'ソ' => 'so' ,
  'タ' => 'ta' ,
  'チ' => 'chi', 
  'ツ' => 'tsu',	
  'テ' => 'te' ,
  'ト' => 'to' ,
  'ナ' => 'na' ,
  'ニ' => 'ni' ,
  'ヌ' => 'nu' ,
  'ネ' => 'ne' ,
  'ノ' => 'no' ,
  'ハ' => 'ha' ,
  'ヒ' => 'hi' ,
  'フ' => 'fu' ,
  'ヘ' => 'he' ,
  'ホ' => 'ho' ,
  'マ' => 'ma' ,
  'ミ' => 'mi' ,
  'ム' => 'mu' ,
  'メ' => 'me' ,
  'モ' => 'mo' ,
  'ヤ' => 'ya' ,
  'ユ' => 'yu' ,
  'ヨ' => 'yo' ,
  'ラ' => 'ra' ,
  'リ' => 'ri' ,
  'ル' => 'ru' ,
  'レ' => 're' ,
  'ロ' => 'ro' ,
  'ワ' => 'wa' ,
  'ヰ' => 'wi' ,
  'ヱ' => 'we' ,
  'ヲ' => 'wo' ,
  'ン' => 'n'  ,
  'ガ' => 'ga' ,
  'ギ' => 'gi' ,
  'グ' => 'gu' ,
  'ゲ' => 'ge' ,
  'ゴ' => 'go' ,
  'ザ' => 'za' ,
  'ジ' => 'ji' ,
  'ズ' => 'zu' ,
  'ゼ' => 'ze' ,
  'ゾ' => 'zo' ,
  'ダ' => 'da' ,
  'ヂ' => 'ji' ,
  'ヅ' => 'zu' ,
  'デ' => 'de' ,
  'ド' => 'do' ,
  'バ' => 'ba' ,
  'ビ' => 'bi' ,
  'ブ' => 'bu' ,
  'ベ' => 'be' ,
  'ボ' => 'bo' ,
  'パ' => 'pa' ,
  'ピ' => 'pi' ,
  'プ' => 'pu' ,
  'ペ' => 'pe' ,
  'ポ' => 'po' 
}
doubles = {
  'くゎ' => 'kwa', 
  'リャ'=> 'rya',
  'リュ'=> 'ryu',
  'ヒャ'=> 'hya',
  'ヒュ'=> 'hyu',
  'ヒョ'=> 'hyo',
  'ミャ'=> 'mya',
  'ニャ'=> 'nya',
  'ニュ'=> 'nyu',
  'ニョ'=> 'nyo',
  'ミュ'=> 'myu',
  'ミョ'=> 'myo',
  'リョ'=> 'ryo',
  'きゃ' => 'kya', 
  'きゅ' => 'kyu', 
  'きょ' => 'kyo',
  'ビャ'=> 'bya',
  'ヰャ'=> 'wya',
  'ヰュ'=> 'wyu',
  'ヰョ'=> 'wyo',
  'ビュ'=> 'byu',
  'ビョ'=> 'byo',
  'ピャ'=> 'pya',
  'ヂャ'=> 'ja' ,
  'ヂュ'=> 'ju' ,
  'ジャ'=> 'ja' ,
  'ジュ'=> 'ju' ,
  'ジョ'=> 'jo' ,
  'ヂョ'=> 'jo' ,
  'ピュ'=> 'pyu',
  'ギャ'=> 'gya',
  'ギュ'=> 'gyu',
  'ギョ'=> 'gyo',
  'シャ'=> 'sha',
  'にゃ'=>'nya'  ,
  'にゅ'=>'nyu'  ,
  'にょ'=>'nyo'  ,
  'ひゃ'=>'hya'  ,
  'ひゅ'=>'hyu'  ,
  'ひょ'=>'hyo'  ,
  'みゃ'=> 'mya' ,
  'みゅ'=> 'myu' ,
  'みょ'=> 'myo' ,
  'りゃ'=> 'rya' ,
  'りゅ'=> 'ryu' ,
  'りょ'=> 'ryo' ,
  'ぐゎ'=> 'gwa' ,
  'ぎゃ'=> 'gya' ,
  'ぎゅ'=> 'gyu' ,
  'ぎょ'=> 'gyo' ,
  'じゃ'=> 'ja'  ,
  'じゅ'=> 'ju'  ,
  'じょ'=> 'jo'  ,
  'ぢゃ'=> 'ja'  ,
  'ぢゅ'=> 'ju'  ,
  'ぢょ'=> 'jo'  ,
  'びゃ'=> 'bya' ,
  'びゅ'=> 'byu' ,
  'びょ'=> 'byo' ,
  'ぴゃ'=> 'pya' ,
  'ぴゅ'=> 'pyu' ,
  'ぴょ'=> 'pyo' ,
  'シュ'=> 'shu',
  'しゃ'=>'sha'  ,
  'しゅ'=>'shu'  ,
  'しょ'=>'sho'  ,
  'ちゃ'=>'cha'  ,
  'ちゅ'=>'chu'  ,
  'ちょ'=>'cho'  ,
  'ショ'=> 'sho',
  'チャ'=> 'cha', 
  'チュ'=> 'chu',	
  'チョ'=> 'cho',
  'キャ'=> 'kya',
  'キュ'=> 'kyu',
  'キョ'=> 'kyo',
  'ピョ'=> 'pyo',
  'イィ' => 'yi',
  'ユェ' => 'ye',
  'イェ' => 'ye',
  'ヴァ' => 'va',
  'ヸ' => 'vi',
  'ヴィ' => 'vi',
  'ヴ' => 'vu',
  'ヹ' => 've',
  'ヴェ' => 've',
  'ヺ' => 'vo',
  'ヴォ' => 'vo',
  'ヴャ' => 'vya',
  'ヴュ' => 'vyu',
  'ヴョ' => 'vyo',
  'シェ' => 'she',
  'ジェ' => 'je',
  'チェ' => 'che',
  'スヮ' => 'swa',
  'スァ' => 'swa',
  'スィ' => 'si',
  'スゥ' => 'swu',
  'スェ' => 'swe',
  'スォ' => 'swo',
  'スャ' => 'sya',
  'スュ' => 'syu',
  'スョ' => 'syo',
  'ズヮ' => 'zwa',
  'ズァ' => 'zwa',
  'ズィ' => 'zi',
  'ズゥ' => 'zwu',
  'ズェ' => 'zwe',
  'ズォ' => 'zwo',
  'ズャ' => 'zya',
  'ズュ' => 'zyu',
  'ズョ' => 'zyo',
  'ツァ' => 'tsa',
  'ツィ' => 'tsi',
  'ツェ' => 'tse',
  'ツォ' => 'tso',
  'テァ' => 'tha',
  'ティ' => 'ti',
  'テゥ' => 'thu',
  'テェ' => 'tye',
  'テォ' => 'tho',
  'テャ' => 'tya',
  'テュ' => 'tyu',
  'テョ' => 'tyo',
  'デァ' => 'dha',
  'ディ' => 'di',
  'デゥ' => 'dhu',
  'デェ' => 'dye',
  'デォ' => 'dho',
  'デャ' => 'dya',
  'デュ' => 'dyu',
  'デョ' => 'dyo',
  'トヮ' => 'twa',
  'トァ' => 'twa',
  'トィ' => 'twi',
  'トゥ' => 'tu',
  'トェ' => 'twe',
  'トォ' => 'two',
  'ドヮ' => 'dwa',
  'ドァ' => 'dwa',
  'ドィ' => 'dwi',
  'ドゥ' => 'du',
  'ドェ' => 'dwe',
  'ドォ' => 'dwo',
  'ホヮ' => 'hwa',
  'ホァ' => 'hwa',
  'ホィ' => 'hwi',
  'ホゥ' => 'hu',
  'ホェ' => 'hwe',
  'ホォ' => 'hwo',
  'ファ' => 'fa',
  'フィ' => 'fi',
  'フェ' => 'fe',
  'フォ' => 'fo',
  'フャ' => 'fya',
  'フュ' => 'fyu',
  'フョ' => 'fyo',
  'リィ' => 'ryi',
  'リェ' => 'rye',
  'ウァ' => 'wa',
  'ウィ' => 'wi',
  'ウゥ' => 'wu',
  'ウー' => 'wu',
  'ウェ' => 'we',
  'ウォ' => 'wo',
  'ウャ' => 'wya',
  'ウュ' => 'wyu',
  'ウョ' => 'wyo',
  'クヮ' => 'kwa',
  'クァ' => 'kwa',
  'クィ' => 'kwi',
  'クゥ' => 'kwu',
  'クェ' => 'kwe',
  'クォ' => 'kwo',
  'グヮ' => 'gwa',
  'グァ' => 'gwa',
  'グィ' => 'gwi',
  'グゥ' => 'gwu',
  'グェ' => 'gwe',
  'グォ' => 'gwo',
  'ムヮ' => 'mwa',
  'ムァ' => 'mwa',
  'ムィ' => 'mwi',
  'ムゥ' => 'mwu',
  'ムェ' => 'mwe',
  'ムォ' => 'mwo'
}
singles = hiragana.merge(katakana)

file = File.new("jap_eng.txt", "r")
#while content = file.gets
2.times {file.gets}
added_words = []
while content = file.gets
  next if content.nil?
  translation = ""
  content = content.strip.chomp
  explanation = file.gets
  explanation.chomp! unless explanation.nil?
  translation = content.dup
  doubles.each do |kana, roma|
    translation.gsub!(kana, roma)
  end
  singles.each do |kana, roma|
    translation.gsub!(kana, roma)
  end
  kind = '4'
  hiragana.keys.each do |h|
    if content.include?(h)
      kind = 0
      break
    end
  end
  katakana.keys.each do |k|
    if content.include?(k)
      kind = 1
      break
    end
  end
  
  translation.gsub!(/(っ)(.)/) {|s| "#{$2}#{$2}"}
  translation.gsub!(/(ッ)(.)/) {|s| "#{$2}#{$2}"}
  translation.gsub!(/(.)(ー)/) do |s|
    if $1 == "o"
      "ou"
    else
      "#{$1}#{$1}"
    end
  end
  
  #puts 'Kana: "' + content + '"'
  #puts 'Romaji: ' + translation
  #puts 'Kind: ' + kind.to_s
  #puts "Test: " + translation.gsub(/[a-z]/,'').length.to_s
  #puts 'Explanation: "' + explanation + '"'
  #puts
  
  # 
  if translation.gsub(/[a-z]/,'').length == 0 && !content.match(/[a-z A-Z]/) && !added_words.include?(translation)
    @db.execute( "insert into words (kind, kana, romaji, meaning, created_at, updated_at) values(?, ?, ?, ?, ?, ?)", kind, content, translation, explanation, Time.now, Time.now)
    added_words << translation
  end
end
file.close